{{- if .Values.ingress.enabled -}}
{{- $fullName := include "cp-control-center.fullname" . -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}-ingress
  labels:
      app: {{ include "cp-control-center.name" . }}
      chart: {{ include "cp-control-center.chart" . }}
      release: {{ .Release.Name }}
      heritage: {{ .Release.Service }}
  annotations:
    {{ if .Values.ingress.annotations }}
 {{ toYaml .Values.ingress.annotations | indent 8 }}
       {{ end }}
spec:
{{- if .Values.ingress.tls }}
  tls:
  {{- range .Values.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
    - host: d-aw2.{{ .Values.ingress.hosts }}.aws.imovetv.com 
      http:
        paths:
          - path: {{ .Values.ingress.path }}
            backend:
              serviceName: {{ template "cp-control-center.fullname" . }}
              servicePort: {{ .Values.serviceHttpPort }}
{{- end }}